[package]
name = "ibkr-flex-statement"
description = "Parser for InteractiveBrokers (IBKR) Flex-based query response XML broker statements."
version = "0.2.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.40"
chrono-tz = "0.10.3"
roxmltree = "0.20.0"
